<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atipico.Aspire.ServiceDefaults\Atipico.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Atipico.Domain\Atipico.Domain.csproj" />
    <ProjectReference Include="..\Atipico.Application\Atipico.Application.csproj" />
  </ItemGroup>

</Project>
