<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ba1e913a-f090-4a09-b872-60c2ff5f7d61</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.3" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atipico.Application\Atipico.Application.csproj" />
    <ProjectReference Include="..\Atipico.Aspire.ServiceDefaults\Atipico.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Atipico.Infraestructure\Atipico.Infraestructure.csproj" />
  </ItemGroup>

</Project>
